/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ElevatorProj_TestPackage;

//import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @authors Andrew Krause, Mitchell Babej, and John Merkel
 */
public class ElevatorTestFrame extends javax.swing.JFrame{

    /* Depricated
    ElevatorSystem elevatorSystem;
    */

    private ElevatorShaft shaft1;
    private ElevatorShaft shaft2;
    
    /**
     * Creates new form ElevatorTestFrame
     */
    public ElevatorTestFrame() {
        
        initComponents();

        shaft1 = new ElevatorShaft("E1");
        shaft1Panel.add(shaft1);
        shaft2 = new ElevatorShaft("E2");
        shaft2Panel.add(shaft2);
    }
    
    private void callNearestElevator(int floorOfCall) {
        
    }
    
    //@Override
    //currently a work in progress
    public void keyReleased(KeyEvent e) throws InterruptedException {
        switch(e.getKeyCode()) {
            case KeyEvent.VK_1 : //user released non-numpad '1' key
                shaft1.moveElevatorTo(0);
                break;

            case KeyEvent.VK_2 : //user released non-numpad '2' key
                shaft1.moveElevatorTo(1);
                break;

            case KeyEvent.VK_3 : //user released non-numpad '3' key
                shaft1.moveElevatorTo(2);
                break;

            case KeyEvent.VK_NUMPAD1 : //user released numpad '1' key
                shaft2.moveElevatorTo(0);
                break;

            case KeyEvent.VK_NUMPAD2 : //user released numpad '2' key
                shaft2.moveElevatorTo(1);
                break;

            case KeyEvent.VK_NUMPAD3 : //user released numpad '3' key
                shaft2.moveElevatorTo(2);
                break;

            case KeyEvent.VK_W : //user released keyboard 'w' key

                break;

            case KeyEvent.VK_A : //user released keyboard 'a' key

                break;

            case KeyEvent.VK_S : //user released keybaord 's' key

                break;

            case KeyEvent.VK_Z : //user released keyboard 'z' key

                break;


            default:
                System.err.println(e.getExtendedKeyCode() + " is an invalid Key Stroke");
                
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameTitle = new javax.swing.JLabel();
        floor3InstructionsDown = new javax.swing.JLabel();
        floor2InstructionsUp = new javax.swing.JLabel();
        floor2InstructionsDown = new javax.swing.JLabel();
        floor1InstructionsUp = new javax.swing.JLabel();
        shaft1Panel = new javax.swing.JPanel();
        shaft2Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        frameTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        frameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameTitle.setText("Elevators");
        frameTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        floor3InstructionsDown.setText("Down: W");

        floor2InstructionsUp.setText("Up: A");

        floor2InstructionsDown.setText("Down: S");

        floor1InstructionsUp.setText("Up: Z");

        shaft1Panel.setMaximumSize(new java.awt.Dimension(103, 239));
        shaft1Panel.setMinimumSize(new java.awt.Dimension(103, 239));
        shaft1Panel.setPreferredSize(new java.awt.Dimension(103, 239));
        shaft1Panel.setLayout(new java.awt.GridBagLayout());

        shaft2Panel.setMaximumSize(new java.awt.Dimension(103, 239));
        shaft2Panel.setMinimumSize(new java.awt.Dimension(103, 239));
        shaft2Panel.setPreferredSize(new java.awt.Dimension(103, 239));
        shaft2Panel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(floor3InstructionsDown))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(floor2InstructionsUp)
                                .addComponent(floor2InstructionsDown)
                                .addComponent(floor1InstructionsUp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shaft1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shaft2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(frameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(floor3InstructionsDown)
                        .addGap(41, 41, 41)
                        .addComponent(floor2InstructionsUp)
                        .addGap(5, 5, 5)
                        .addComponent(floor2InstructionsDown)
                        .addGap(35, 35, 35)
                        .addComponent(floor1InstructionsUp))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shaft2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shaft1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        try {
            keyReleased(evt);
        } catch (InterruptedException ex) {
            Logger.getLogger(ElevatorTestFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElevatorTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel floor1InstructionsUp;
    private javax.swing.JLabel floor2InstructionsDown;
    private javax.swing.JLabel floor2InstructionsUp;
    private javax.swing.JLabel floor3InstructionsDown;
    private javax.swing.JLabel frameTitle;
    private javax.swing.JPanel shaft1Panel;
    private javax.swing.JPanel shaft2Panel;
    // End of variables declaration//GEN-END:variables
}
