/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ElevatorProj_TestPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author John
 */
public class ElevatorShaft extends JPanel {
    
    private static final int DOOR_TIME     = 2000;
    private static final int ELEVATOR_TIME = 6000;
    
    private String name = "";
    
    private ArrayList<DoorLabel> shaft;
    private int currentFloor = 0;
    private int goalFloor;
    private boolean doorIsOpen         = false;
    private boolean isAnimated         = false;
    private boolean doorCloseThenMoves = false;
    private Timer openDoorsTimer;
    private Timer closeDoorsTimer;
    private Timer moveElevatorTimer;
    
    /**
     * Creates new form ElevatorShaft
     * @param InitialName Name for the particular instance of ElevatorShaft
     */
    public ElevatorShaft(String InitialName) {
        name = InitialName;
        
        shaft = new ArrayList<>();
        
        openDoorsTimer    = new Timer(DOOR_TIME, openDoors);
        closeDoorsTimer   = new Timer(DOOR_TIME, closeDoors);
        moveElevatorTimer = new Timer(ELEVATOR_TIME, moveElevator);
        openDoorsTimer   .setRepeats(false);
        closeDoorsTimer  .setRepeats(false);
        moveElevatorTimer.setRepeats(false);
        
        initComponents();
        
        DoorLabel newDoor;
        
        newDoor = new DoorLabel(name + "_F1");
        newDoor.openDoors();
        floor1.add(newDoor);
        shaft.add(newDoor);
        
        newDoor = new DoorLabel(name + "_F2");
        floor2.add(newDoor);
        shaft.add(newDoor);
        
        newDoor = new DoorLabel(name + "_F3");
        floor3.add(newDoor);
        shaft.add(newDoor);
        
        shaft.get(0).setBackground(DoorLabel.SECONDARY);
        shaft.get(0).setText("=][=");
        floorTracker.setText("" + (currentFloor + 1));
    }
    
    public String getShaftName() {
        return name;
    }
    
    //Opens the doors on the elevator in the desired 'shaft'
    public void openDoors() {
        if(!isAnimated){
            isAnimated = true;
            openDoorsTimer.start();
        }
    }
    
    ActionListener openDoors = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            shaft.get(currentFloor).openDoors();
            doorIsOpen = true;
            closeDoorsTimer.start();
        }};
    
    //Closes the doors on the elevator in the desired 'shaft'
    public void closeDoors() {
        if(!isAnimated){
           isAnimated = true;
           closeDoorsTimer.start(); 
        }
    }
    
    ActionListener closeDoors = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            shaft.get(currentFloor).closeDoors();
            doorIsOpen = false;
            if(doorCloseThenMoves){
                moveElevatorTimer.start();
            } else { 
                isAnimated = false;
            }
        }};
    
    //Currently a work in progress
    public void moveElevatorTo(int destination) {
        if(currentFloor == destination) {
            System.out.println("Already at desired floor");
            return;
        } else if (destination > 2 || destination < 0) {
            System.err.println("Invalid floor number");
            System.out.println("Please refer to floors by index value");
            return;
        }
        isAnimated = true;
        goalFloor = destination;
        if(doorIsOpen){
            doorCloseThenMoves = true;
            closeDoorsTimer.start();
        } else {
            moveElevatorTimer.start();
        }
    }
    
    ActionListener moveElevator = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            shaft.get(currentFloor++).setEmpty();
            floorTracker.setText("" + (currentFloor + 1));
            shaft.get(currentFloor).closeDoors();
            if(currentFloor == goalFloor){
                openDoorsTimer.start();
            } else { 
                moveElevatorTo(goalFloor);
            }
        }};
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floorTracker = new javax.swing.JLabel();
        floor3 = new javax.swing.JPanel();
        floor2 = new javax.swing.JPanel();
        floor1 = new javax.swing.JPanel();

        floorTracker.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        floorTracker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorTracker.setText("#");
        floorTracker.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        floor3.setMaximumSize(new java.awt.Dimension(91, 40));
        floor3.setMinimumSize(new java.awt.Dimension(91, 40));
        floor3.setPreferredSize(new java.awt.Dimension(91, 40));
        floor3.setLayout(new java.awt.GridBagLayout());

        floor2.setMaximumSize(new java.awt.Dimension(91, 40));
        floor2.setMinimumSize(new java.awt.Dimension(91, 40));
        floor2.setPreferredSize(new java.awt.Dimension(91, 40));
        floor2.setLayout(new java.awt.GridBagLayout());

        floor1.setMaximumSize(new java.awt.Dimension(91, 40));
        floor1.setMinimumSize(new java.awt.Dimension(91, 40));
        floor1.setPreferredSize(new java.awt.Dimension(91, 40));
        floor1.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(floorTracker))
                    .addComponent(floor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(floorTracker)
                .addGap(18, 18, 18)
                .addComponent(floor3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(floor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(floor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel floor1;
    private javax.swing.JPanel floor2;
    private javax.swing.JPanel floor3;
    private javax.swing.JLabel floorTracker;
    // End of variables declaration//GEN-END:variables
}
