/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ElevatorProj_TestPackage;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author John
 */
public class ElevatorLabel extends JLabel {
    String name = "";
    public static final Color PRIMARY   = new Color( 84, 238,  73);
    public static final Color SECONDARY = new Color(255, 255,   0);
    public static final Color NONE      = new Color(214, 217, 223);
    /**
     * Creates new form ElevatorLabel
     */
    public ElevatorLabel() {
        initComponents();
    }
    //Overloaded constructor
    public ElevatorLabel(String name) {
        initComponents();
        this.name = name;
    }
    
    public String getLabelName() {
        return name;
    }

    public void openDoors() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ElevatorLabel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setText("]  [");
        this.setBackground(PRIMARY);
    }
    
    public void closeDoors() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ElevatorLabel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setText("=][=");
        this.setBackground(SECONDARY);
    }
    
    public void noElevator() {
        this.setBackground(NONE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setText("=][=");
        setVerticalAlignment(javax.swing.SwingConstants.TOP);
        setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setMaximumSize(new java.awt.Dimension(52, 33));
        setMinimumSize(new java.awt.Dimension(52, 33));
        setName(""); // NOI18N
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(52, 33));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
