/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package STEMproj_TestPackage;

/**
 *
 * @author a-krause
 */
public class ElevatorTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form ElevatorTestFrame
     */
    public ElevatorTestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elevator1FloorLabel = new javax.swing.JLabel();
        elevator2FloorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        door1Label = new javax.swing.JLabel();
        door2Label = new javax.swing.JLabel();
        door3Label = new javax.swing.JLabel();
        door4Label = new javax.swing.JLabel();
        door5Label = new javax.swing.JLabel();
        door6Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        elevator1FloorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        elevator1FloorLabel.setText("1");

        elevator2FloorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        elevator2FloorLabel.setText("3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Elevators");

        door1Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        door1Label.setText("=][=");

        door2Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        door2Label.setText("=][=");

        door3Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        door3Label.setText("]    [");

        door4Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        door4Label.setText("=][=");

        door5Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        door5Label.setText("=][=");

        door6Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        door6Label.setText("=][=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(elevator1FloorLabel)
                        .addGap(83, 83, 83)
                        .addComponent(elevator2FloorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(door3Label)
                            .addComponent(door2Label)
                            .addComponent(door1Label))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(door4Label)
                            .addComponent(door5Label)
                            .addComponent(door6Label))))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elevator2FloorLabel)
                    .addComponent(elevator1FloorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(door1Label)
                    .addComponent(door4Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(door5Label)
                    .addComponent(door2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(door6Label)
                    .addComponent(door3Label))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElevatorTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElevatorTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel door1Label;
    private javax.swing.JLabel door2Label;
    private javax.swing.JLabel door3Label;
    private javax.swing.JLabel door4Label;
    private javax.swing.JLabel door5Label;
    private javax.swing.JLabel door6Label;
    private javax.swing.JLabel elevator1FloorLabel;
    private javax.swing.JLabel elevator2FloorLabel;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
